// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://muqbkczthcijjjjvnivs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11cWJrY3p0aGNpampqanZuaXZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1Mzc2ODcsImV4cCI6MjA2OTExMzY4N30.bCGDXv8P6J_sPHa0iR7urzCsJufVzBZTlnjHhC0kAtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});